name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# ↓↓↓ この5行を新しく追加してください ↓↓↓
permissions:
  contents: read
  pages: write
  id-token: write
# ↑↑↑ ここまで ↑↑↑

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10.2.1
          run_install: false

      - name: Generate Pages
        run: |
          pnpm install --no-frozen-lockfile
          pnpm --filter=@shadergradient/react release:framer
          pnpm --filter=ui release

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'packages/shadergradient/release'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4