name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10.2.1
          run_install: false

      - name: Generate Pages
        run: |
          pnpm install --no-frozen-lockfile
          # Framer用のリリースファイルを生成
          pnpm --filter=@shadergradient/react release:framer
          # UIパッケージのリリースファイルを生成
          pnpm --filter=ui release
          # Next.js のビルド（静的エクスポートを実行し、outフォルダを出力させます）
          pnpm --filter=example-nextjs-dev build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # アップロードする対象を、生成された「out」フォルダに変更します
          path: 'apps/example-nextjs-dev/out'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4